-- H2
--CREATE TABLE IF NOT EXISTS heroe (
--  id bigint NOT NULL AUTO_INCREMENT,
--  name varchar(255) DEFAULT NULL,
--  PRIMARY KEY (id)
--);

-- PostgreSql

-- DROP TABLE public.heroe;

CREATE TABLE IF NOT EXISTS public.heroe
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT heroe_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.heroe
    OWNER to postgres;



-- DROP TABLE public.users  ;

CREATE TABLE IF NOT EXISTS public.users
    (
        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        name character varying(255) COLLATE pg_catalog."default",
        pass character varying(255) COLLATE pg_catalog."default",
        CONSTRAINT users_pkey PRIMARY KEY (id)
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    ALTER TABLE public.users
        OWNER to postgres;